### ISSUE TITLE
[RFC] [pub-content-title]

### ISSUE THREAD

**Issue by simon-debruijn** [cultuurnet/udb3-frontend#77]
## Use case

This component will be used as a title inside sections, articles and divs. If we see pub-page-title as our heading 1, the pub-content-title is heading 2. This component will be used when the content of a page requires a title.

## Existing examples in the Legacy UI and/or Vue app

![Schermafbeelding 2020-09-18 om 09 15 52](https://user-images.githubusercontent.com/66943525/93569076-5c293500-f991-11ea-93b6-7aef2dfee5a3.png)
![Schermafbeelding 2020-09-18 om 09 16 07](https://user-images.githubusercontent.com/66943525/93569079-5cc1cb80-f991-11ea-8a5d-74766217face.png)
![Schermafbeelding 2020-09-18 om 09 24 22](https://user-images.githubusercontent.com/66943525/93569082-5d5a6200-f991-11ea-8fd4-af61d4b7acee.png)

These are all h2 tags that are styled slightly differently. They differ in the font-size which is 1rem or 1.2rem. They also differ in casing: normal casing or uppercasing.

A variant could be the uppercased title, which we will not yet implement until needed for the 'invoeren' page of an event.

## Proposed styling

We can style the pub-content-title to a font-size of 1.2 rem and with a font-weight (which is the same on all examples) of 700.

## Proposed props

Only the slot is passed through

In the future maybe variant prop or uppercase boolean prop.

## Proposed actions

None

**Comment by bertramakers** [comment]
✅ Agreed about the style being:

```
font-size: 1.2rem
font-weight: 700
```

✅ Agreed about adding a capitalized variant (if still needed by that point)

❓ Not sure about the `pub-content-title` name. `content-tile` feels a bit vague since every heading is technically a content title. And taking a step back and looking at the bigger picture, how would we name `h3`, `h4`, etc? Don't have a counter-proposal myself right now. The only potential solution I see right now is switching back to `heading-1`, `heading-2` or something similar. @geoffreydhuyvetters maybe you have an idea? Or am I overthinking it and is `pub-content-title` fine?

**Comment by simon-debruijn** [comment]
We could name all further headings pub-content-title and pass a size prop. So we have a pub-page-title and then different variants for the pub-content-title?

**Comment by simon-debruijn** [comment]
It could be `<pub-content-title />` of maybe `<pub-title  />`

with the option for 

- a variant:
`<pub-title variant="h1" />`, `<pub-title variant="h2" />`

OR

- a size:
`<pub-title size="1" />`, `<pub-title size="2" />`

OR

- a boolean prop
`<pub-title h1 />`, `<pub-title h2 />`

**Comment by bertramakers** [comment]
Yeah good idea, I like `pub-title`!

Personally I'd go with the `size` prop.

I'm not a fan of the boolean props like `<pub-title h1 />`, `<pub-title h2 />`, ... because then it's easy to make a mistake and do something like `<pub-title h1 h2 />`. Documentation and controls in Storybook would also become more confusing (6 boolean toggles instead of a combo box with options)

The `variant` with `h1`, `h2`, is technically also fine by me. Maybe the `h1`, `h2`, etc are just implementation details though, which is why my personal preference would go to the `size="1"`, `size="2"` prop.

I think @geoffreydhuyvetters suggested a while back somewhere to go with something like `level`. Could also be a good alternative to `size`. But the way of working would be the same, just a different name. So I don't have a strong preference for one or the other.
