### ISSUE TITLE
[RFC] Design tokens

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [cultuurnet/udb3-frontend#90]
In order to make the UI consistent we need some design tokens.

> With design tokens, you can capture low-level values and then use them to create the styles for your product or app. You can maintain a scalable and consistent visual system for UI development. 

# Reference
- https://github.com/sturobson/Awesome-Design-Tokens
- https://designsystemchecklist.com/category/design-tokens/
- https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62
- https://medium.com/eightshapes-llc/color-in-design-systems-a1c80f65fa3
- https://medium.com/eightshapes-llc/typography-in-design-systems-6ed771432f1e

# Todo

- [ ] visualize in storybook

## Specifics

# Colors

- define essential brand colours and name them as such (primary)
- Do we need colour modifiers?
- Auto-generated or handpicked?
- Limiting the options.
- generic feedback colours (success, warning, error, info)

# Spacing

https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62

simple numeric values (0, 1, 2, 3, 4...) and convert them

- 0 = 0 = none
- 1 = 2px = xxs
- 2 = 4px = xs 
- 3 = 8px = s
- **4 = 16px = m**
- 5 = 32px = l
- 6 = 64px = xl
- 7 = 128px = xxl
- 8 = 256px
- ...

Convert to REM equivalents.

Those will be used on some of the primitive components we need to create, Stack / Inline.

# Font sizes

set base font size as REM and provide multiples for headers/text etc
Don't mix levels with actual h# levels

- 1 
- 2
- 3
- 4 = L
- **5 = M**
- S
- XS

## Theming

- how do we handle theming?

**Comment by bertramakers** [comment]
Thanks, it's a good start to get the conversation going I think!

Going to read through it in detail tomorrow, but as a quick note, we currently have `1rem = 15px` if I'm not mistaken.
We could change that of course, but it would require some adjustments here and there to get everything looking consistent in size with the old app again.

I think having it set as `16px` or another multiple of 2 would make more sense though. Because right now we have `0.5rem` in some places which results in `7.5px` which is not ideal.

**Comment by geoffreydhuyvetters** [comment]
Yeah, it will be a massive task to create consistent design tokens based on a design that didn't bother about it all.

**Comment by bertramakers** [comment]
Oh I meant we use `1rem = 15px` in the new app right now. So if we change that to `16px` either we will have to adjust all of the new styles, or we keep the rems the same but everything looks _slightly_ bigger. Not that I'm not okay with that, just mentioning what a change to `16px` would mean. But I think in the long run it will result in more consistent and faster designing.

For reference: In the old app I think `1rem = 10px`. But I'd have to double check.

But yeah I don't think any of that (new or old rems) was a conscious decision. I think it's just what Bootstrap 3 and 4 use. Or maybe changed on a whim because the person who set it to `10px` thought it might make calculations easier or something like that.

I'll read through your references today. At this point I'm mostly curious how we would technically implement it, as I've never worked with design tokens before.

**Comment by simon-debruijn** [comment]
I would also opt for using `16px` as our base font size. 

What I'm wondering about is, will we use `.scss` files to declare our tokens (other options could be `.yml`, `.js` or `.json` )? And how will we use / pass these tokens (e.g. $primary-color) to a component?  Will we pass a prop like `space` or` size` with value a `0-...`  and then convert that value into the matching classes in the component that contain the correct tokens, or will we pass tokens by inline styles? Idk if you had a specific approach  in mind @geoffreydhuyvetters?  

I also think this could be a cool repo to take a look at, it's design tokens implemented in vue:
[vue-cion-design-system](https://github.com/visualjerk/vue-cion-design-system)

**Comment by bertramakers** [comment]
From the (very) limited reading I did so far, I think the idea is that they will become CSS/SCSS variables to use in your stylesheets. So if you only need them in a web app, that's the easiest way. But if you also have other apps, e.g. native iOS, Android, macOS, Linux, Windows, ... app you can first define them in JSON/yml and then automatically convert them to CSS in a later step so all tokens start from a single source of truth and then get converted to the required formats for all those platforms? But feel free to correct me if this interpretation is wrong.

**Comment by bertramakers** [comment]
@geoffreydhuyvetters I think it might help if you could add some code blocks with pseudo-code examples of how some of these tokens would be passed to a concrete component, how it would work inside the base component, etc. Aside from the concrete kinds of design tokens and their specific values. Right now it's still a bit abstract to me how we would end up using the design tokens, which makes it a bit harder to grasp for me.

**Comment by geoffreydhuyvetters** [comment]
> I would also opt for using 16px as our base font size.

This is purely an example of how these tokens could work, didn't look at the actual values yet.

> Right now it's still a bit abstract to me how we would end up using the design tokens, which makes it a bit harder to grasp for me.

You would have a property spacing, for example. If you pass it '3' it would internally be translated to the correct value on our scale.
